[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
select = ["E","F","I","UP","B","SIM","W"]
ignore = ["E501"]
target-version = "py311"

[tool.ruff.format]
quote-style = "double"

