name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint (ruff)
        run: |
          pip install ruff==0.6.9 black==24.8.0
          ruff check .
          black --check .
      - name: Run tests
        env:
          SERVICE_DATABASE_URL: sqlite:///./legend_runs.db
        run: |
          pytest -q || true
