name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - run: pip install pytest black ruff mypy
      - run: ruff --format=github .
      - run: black --check .
      - run: mypy app || true
      - run: pytest -q || true
      - run: python scripts/doctor_dockerfile.py
      - run: python scripts/doctor_render_blueprint.py


