name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black mypy
      - name: Lint (ruff)
        run: ruff check .
      - name: Format check (black)
        run: black --check .
      - name: Type check
        run: mypy --ignore-missing-imports . || true
      - name: Tests
        run: pytest -q

  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: kyle-portfolio/package-lock.json
      - name: Install
        working-directory: kyle-portfolio
        run: npm ci
      - name: Lint (Next)
        if: exists('kyle-portfolio/package.json')
        working-directory: kyle-portfolio
        run: npm run lint --if-present
      - name: Build
        working-directory: kyle-portfolio
        run: npm run build --if-present
