name: Deploy (Render + Vercel)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Trigger Render deploys (API + shots)
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
          API_SERVICE_ID: ${{ secrets.API_SERVICE_ID }}
          SHOTS_SERVICE_ID: ${{ secrets.SHOTS_SERVICE_ID }}
        run: |
          set -euo pipefail
          if [ -z "${RENDER_TOKEN}" ]; then
            echo "No RENDER_TOKEN; skipping Render deploys."
            exit 0
          fi
          trigger() {
            local sid="$1" label="$2"
            if [ -z "$sid" ]; then
              echo "Skipping $label (no service id)"; return 0; fi
            echo "Trigger $label …"
            curl -fsS -X POST "https://api.render.com/v1/services/${sid}/deploys" \
              -H "Authorization: Bearer ${RENDER_TOKEN}" -H "Accept: application/json" -H "Content-Type: application/json" -d '{}' \
              | tee deploy_${label}.json
          }
          trigger "${API_SERVICE_ID:-}" api || true
          trigger "${SHOTS_SERVICE_ID:-}" shots || true

      - name: Trigger Vercel Deploy Hook
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "${VERCEL_DEPLOY_HOOK_URL}" ]; then
            echo "No Vercel hook; skipping"
            exit 0
          fi
          curl -fsS -X POST "$VERCEL_DEPLOY_HOOK_URL" -o /dev/null
          echo "Vercel hook sent"
